import sys

#Composer will generate non-complex SQL queries.  Anything too complex will be generated by the SQLService.
class Composer:
    def __init__(self, data):
        self.release = False
        self.database = data
        return

    #Adds a customer to the customers table
    def add_customer(self):
        cust = {'customer_id':'','company_name ':'','contact_name':'','contact_title':'',
            'address':'','city':'','region':'','postal_code':'','country':'',
            'phone':'','fax':''
        }
        print("Please enter in necessary details")
        for key in cust.keys():
            cust[key] = input(f"{key.upper()}: ")
            sys.stdout.flush()

        if(self.verify(cust) == True):
            return cust
        else:
            return False
    
    #Gets data for an order, sends it over to the SQLService as it is a complex query.
    def add_order(self):
        order = {'customer_id':'','employee_id':'',
            'order_date':'','required_date':'','ship_name':'','ship_address':'',
            'ship_city':'','ship_region':'','ship_postal_code':'',
            'ship_country':'','product_id':'','unit_price':'','quantity':'',
            'discount':''
        }

        for key in order.keys():
            order[key] = input(f"{key.upper()}: ")
        
        if(self.verify(order) == True):
            return order
        else:
            return False
        
    def remove_order(self):
        ord = input("Enter the Order ID of the order you wish to remove: ")
        if(input("Are you sure you wish to delete this order? (y/n) ") == 'y'):
            return ord
        return False

    def ship_order(self):
        info = {'order_id':'','shipped_date': '', 'ship_via':'','freight':''}

        for key in info.keys():
            info[key] = input(f"{key.upper()}: ")

        if(self.verify(info) == True):
            return info
        else:
            return False

    #Verifies that the user wants to complete their transaction.
    def verify(self, arr:dict):
        ret = "Is this correct? (y/n)\n"
        for item_name, item_value in arr.items():
            ret +=(f'{item_name.upper()}: {item_value}\n')
        print(ret)

        while(True):
            val = input("Confirm (y/n) >")
            if(val == 'y'):
                return True
            elif(val == 'n'):
                return False
